services:
  debian11:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile.debian
    container_name: debian11_container
    command: /bin/bash
    volumes:
      - ./data:/data
    tty: true
    stdin_open: true
  centos7:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile.centos
    container_name: centos7_container
    privileged: true
    command: 
      - /bin/bash
    volumes:
      - ./data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /run
    tty: true
    stdin_open: true
