FROM debian:11

RUN apt update

RUN apt install -y sudo nano net-tools netplan.io network-manager dbus systemd systemd-sysv
COPY /data/lab-1 /data/lab-1

RUN echo "root:root" | chpasswd

CMD [ "/bin/bash" "/ns/net" ]